import { Activity, Client, Deal, DealStage, Task } from './types';

// Helper to generate dynamic dates relative to today
const getRelativeDate = (daysOffset: number, iso: boolean = true) => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  // Ensure we don't return negative time if offset is large negative, though Date handles it.
  return iso ? date.toISOString() : date.toISOString().split('T')[0];
};

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Sarah Miller',
    company: 'Apex Design Studio',
    email: 'sarah@apexdesign.com',
    phone: '+1 (555) 012-3456',
    avatar: 'https://picsum.photos/200/200?random=1',
    status: 'Active',
    lastContact: getRelativeDate(-3), // 3 days ago
    nextAction: 'Send revised contract',
    nextActionDate: getRelativeDate(2), // 2 days from now
  },
  {
    id: 'c2',
    name: 'James Chen',
    company: 'Quantum Dynamics',
    email: 'james.c@quantum.io',
    phone: '+1 (555) 987-6543',
    avatar: 'https://picsum.photos/200/200?random=2',
    status: 'Active',
    lastContact: getRelativeDate(-5),
    nextAction: 'Schedule technical review',
    nextActionDate: getRelativeDate(4),
  },
  {
    id: 'c3',
    name: 'Elena Rodriguez',
    company: 'EcoLiving Inc.',
    email: 'elena@ecoliving.org',
    phone: '+1 (555) 456-7890',
    avatar: 'https://picsum.photos/200/200?random=3',
    status: 'Inactive',
    lastContact: getRelativeDate(-45),
    nextAction: 'Quarterly check-in',
    nextActionDate: getRelativeDate(14),
  },
  {
    id: 'c4',
    name: 'Olivia Sterling',
    company: 'Sterling Artistry',
    email: 'olivia@sterlingart.com',
    phone: '+1 (555) 234-5678',
    avatar: 'https://picsum.photos/200/200?random=4',
    status: 'Active',
    lastContact: getRelativeDate(-1),
    nextAction: 'Review portfolio draft',
    nextActionDate: getRelativeDate(3),
  },
  {
    id: 'c5',
    name: 'Marcus Thorne',
    company: 'Thorne Logistics',
    email: 'm.thorne@thornelogistics.com',
    phone: '+1 (555) 876-5432',
    avatar: 'https://picsum.photos/200/200?random=5',
    status: 'Inactive',
    lastContact: getRelativeDate(-60),
    nextAction: 'Re-engagement campaign',
    nextActionDate: getRelativeDate(30),
  },
  {
    id: 'c6',
    name: 'Emily Chen',
    company: 'BrightPath Education',
    email: 'emily@brightpath.edu',
    phone: '+1 (555) 345-6789',
    avatar: 'https://picsum.photos/200/200?random=6',
    status: 'Active',
    lastContact: getRelativeDate(-2),
    nextAction: 'Finalize curriculum proposal',
    nextActionDate: getRelativeDate(1),
  },
  {
    id: 'c7',
    name: 'David Kim',
    company: 'Kim & Associates',
    email: 'dkim@kalegal.com',
    phone: '+1 (555) 654-3210',
    avatar: 'https://picsum.photos/200/200?random=7',
    status: 'Active',
    lastContact: getRelativeDate(-7),
    nextAction: 'Schedule partner meeting',
    nextActionDate: getRelativeDate(5),
  },
  {
    id: 'c8',
    name: 'Sophia Williams',
    company: 'BlueWave Tech',
    email: 'sophia@bluewave.io',
    phone: '+1 (555) 432-1098',
    avatar: 'https://picsum.photos/200/200?random=8',
    status: 'Active',
    lastContact: getRelativeDate(-10),
    nextAction: 'Demo new features',
    nextActionDate: getRelativeDate(2),
  },
  {
    id: 'c9',
    name: 'Lucas Gray',
    company: 'Gray Structural',
    email: 'lucas@graystruct.com',
    phone: '+1 (555) 789-0123',
    avatar: 'https://picsum.photos/200/200?random=9',
    status: 'Inactive',
    lastContact: getRelativeDate(-90),
  },
  {
    id: 'c10',
    name: 'Ava Patel',
    company: 'GreenLeaf Organics',
    email: 'ava@greenleaf.org',
    phone: '+1 (555) 210-9876',
    avatar: 'https://picsum.photos/200/200?random=10',
    status: 'Active',
    lastContact: getRelativeDate(-4),
    nextAction: 'Discuss packaging design',
    nextActionDate: getRelativeDate(3),
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'd1',
    title: 'Q4 Marketing Campaign',
    clientId: 'c1',
    value: 12500,
    stage: DealStage.QUOTE,
    probability: 60,
    expectedCloseDate: getRelativeDate(15, false), // 15 days out
    lastActivityDate: getRelativeDate(-3),
    priority: 'High',
    nextAction: 'Follow up on proposal',
  },
  {
    id: 'd2',
    title: 'Website Redesign',
    clientId: 'c2',
    value: 8000,
    stage: DealStage.NEGOTIATE,
    probability: 80,
    expectedCloseDate: getRelativeDate(5, false), // closing soon
    lastActivityDate: getRelativeDate(-2),
    priority: 'Medium',
    nextAction: 'Finalize scope addendum',
  },
  {
    id: 'd3',
    title: 'Brand Identity',
    clientId: 'c3',
    value: 4500,
    stage: DealStage.LEAD,
    probability: 20,
    expectedCloseDate: getRelativeDate(45, false),
    lastActivityDate: getRelativeDate(-45), // Stalled
    priority: 'Low',
    nextAction: 'Initial discovery call',
  },
  {
    id: 'd4',
    title: 'SEO Retainer',
    clientId: 'c1',
    value: 2000,
    stage: DealStage.WON,
    probability: 100,
    expectedCloseDate: getRelativeDate(-10, false),
    lastActivityDate: getRelativeDate(-10),
    priority: 'Medium',
  },
  {
    id: 'd5',
    title: 'Mobile App UX Audit',
    clientId: 'c2',
    value: 5500,
    stage: DealStage.QUALIFY,
    probability: 40,
    expectedCloseDate: getRelativeDate(25, false),
    lastActivityDate: getRelativeDate(-8),
    priority: 'Medium',
    nextAction: 'Send portfolio examples',
  },
  {
    id: 'd6',
    title: 'Enterprise Consultation',
    clientId: 'c3',
    value: 25000,
    stage: DealStage.QUOTE,
    probability: 50,
    expectedCloseDate: getRelativeDate(60, false),
    lastActivityDate: getRelativeDate(-1),
    priority: 'High',
    nextAction: 'Prepare pricing tiers',
  },
  {
    id: 'd7',
    title: 'Gallery Showcase Event',
    clientId: 'c4',
    value: 15000,
    stage: DealStage.NEGOTIATE,
    probability: 75,
    expectedCloseDate: getRelativeDate(10, false),
    lastActivityDate: getRelativeDate(-1),
    priority: 'High',
    nextAction: 'Confirm venue booking details',
  },
  {
    id: 'd8',
    title: 'LMS Platform Integration',
    clientId: 'c6',
    value: 42000,
    stage: DealStage.QUALIFY,
    probability: 30,
    expectedCloseDate: getRelativeDate(90, false),
    lastActivityDate: getRelativeDate(-2),
    priority: 'High',
    nextAction: 'Schedule technical discovery',
  },
  {
    id: 'd9',
    title: 'Legal Firm Rebranding',
    clientId: 'c7',
    value: 18500,
    stage: DealStage.QUOTE,
    probability: 55,
    expectedCloseDate: getRelativeDate(20, false),
    lastActivityDate: getRelativeDate(-7),
    priority: 'Medium',
    nextAction: 'Present initial concepts',
  },
  {
    id: 'd10',
    title: 'SaaS Product Launch',
    clientId: 'c8',
    value: 30000,
    stage: DealStage.LEAD,
    probability: 10,
    expectedCloseDate: getRelativeDate(120, false),
    lastActivityDate: getRelativeDate(-10),
    priority: 'Medium',
    nextAction: 'Send NDA',
  },
  {
    id: 'd11',
    title: 'Sustainable Packaging Design',
    clientId: 'c10',
    value: 9500,
    stage: DealStage.NEGOTIATE,
    probability: 85,
    expectedCloseDate: getRelativeDate(7, false),
    lastActivityDate: getRelativeDate(-4),
    priority: 'High',
    nextAction: 'Finalize material specs',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Send revised proposal to Apex',
    dueDate: getRelativeDate(1), // Tomorrow
    completed: false,
    priority: 'High',
    relatedClientId: 'c1',
    relatedDealId: 'd1',
  },
  {
    id: 't2',
    title: 'Follow up with James regarding contract',
    dueDate: getRelativeDate(2),
    completed: false,
    priority: 'Medium',
    relatedClientId: 'c2',
    relatedDealId: 'd2',
  },
  {
    id: 't3',
    title: 'Update portfolio with EcoLiving project',
    dueDate: getRelativeDate(-2),
    completed: true,
    priority: 'Low',
  },
  {
    id: 't4',
    title: 'Prepare presentation for Sterling Artistry',
    dueDate: getRelativeDate(0), // Today
    completed: false,
    priority: 'High',
    relatedClientId: 'c4',
    relatedDealId: 'd7',
  },
  {
    id: 't5',
    title: 'Research LMS vendors for BrightPath',
    dueDate: getRelativeDate(3),
    completed: false,
    priority: 'Medium',
    relatedClientId: 'c6',
    relatedDealId: 'd8',
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    clientId: 'c1',
    type: 'Email',
    content: 'Sent initial proposal draft for review.',
    date: getRelativeDate(-3),
  },
  {
    id: 'a2',
    clientId: 'c1',
    type: 'Call',
    content: 'Discussed project scope adjustments. Client wants to add a blog section.',
    date: getRelativeDate(-5),
  },
  {
    id: 'a3',
    clientId: 'c2',
    type: 'Meeting',
    content: 'Discovery session. Key goals: Speed and Mobile responsiveness.',
    date: getRelativeDate(-6),
  },
  {
    id: 'a4',
    clientId: 'c4',
    type: 'Meeting',
    content: 'Gallery walkthrough to understand spatial requirements for the digital showcase.',
    date: getRelativeDate(-1),
  },
];